### PR TITLE
Update to version 5.4.2

### PR DESCRIPTION
**Pull request by mkl262**

### CODE REVIEW

**Comment by mkl262** [comment]
Should I add the dockerfiles to this PR?

**Comment by sergey-safarov** [comment]
Docker packages exist.
You can check here
https://github.com/kamailio/kamailio-ci/tree/master/alpine

**Comment by mkl262** [comment]
I need a bionic image, the kamailio-ci images are alpine only.

**Comment by linuxmaniac** [comment]
https://github.com/kamailio/kamailio-docker/commit/f8fbfe806bad2916957432904848c99fca4f8b8b

**Pull request closed without merging**
