### PR TITLE
Update package version to match upstream

### PR DESCRIPTION
**Pull request by kristianpaul**

### CODE REVIEW

**Comment by kristianpaul** [comment]
Anyone?

**Comment by henningw** [comment]
Thank you for this, it was unfortunately forgotten. Great that you pinged us again.
I will have a look later to today to it.

**Comment by henningw** [comment]
Hi Cristian, would it not make sense to just go to the latest version 5.0.7 in the docker file?

**Comment by kristianpaul** [comment]
> Hi Cristian, would it not make sense to just go to the latest version 5.0.7 in the docker file?

Makes sense

https://github.com/kamailio/kamailio-docker/pull/6

**Comment by linuxmaniac** [comment]
master branch is just the base for the version branches, is not used for the [docker build](https://hub.docker.com/r/kamailio/kamailio/tags/) at all so makes no sense to update the version at all.

In 053355c9fb4e630f27d4c92e48bdcf7326dcdffc I allow to set DISTS and VERSION so you can play with it. Anyhow right now the problem here is that out deb repository can only have one version at the same time so older debs, for instance, 5.0.6 can not be installed using kamalio50 (latest is 5.0.7)

So this repo is a source to build "official" docker images on hub.docker.com automatically

**Comment by henningw** [comment]
@linuxmaniac @kristianpaul  - sorry I did not know the details here. I will extend the readme a bit in this regards.

**Pull request closed without merging**
